/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Z8EFUlLpCBd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Chat() {
  return (
    <div className="flex flex-col h-[500px] border rounded-lg overflow-hidden justify-end">
      <div className="flex-1 overflow-auto p-4">
        <div className="flex flex-col gap-4">
          <div className="flex justify-end">
            <div className="bg-gray-100 px-4 py-3 rounded-lg max-w-[75%] text-sm">Hey there! How's it going?</div>
          </div>
          <div className="flex justify-start">
            <div className="bg-gray-800 text-white px-4 py-3 rounded-lg max-w-[75%] text-sm">
              I'm doing great, thanks for asking! How about you?
            </div>
          </div>
          <div className="flex justify-end">
            <div className="bg-gray-100 px-4 py-3 rounded-lg max-w-[75%] text-sm">
              I'm doing well too, just busy with work. But it's nice to take a break and chat.
            </div>
          </div>
          <div className="flex justify-start">
            <div className="bg-gray-800 text-white px-4 py-3 rounded-lg max-w-[75%] text-sm">
              I hear you. It's important to find that work-life balance. How about we plan to grab coffee later this
              week?
            </div>
          </div>
          <div className="flex justify-start">
            <div className="bg-gray-800 text-white px-4 py-3 rounded-lg max-w-[75%] text-sm">
              I hear you. It's important to find that work-life balance. How about we plan to grab coffee later this
              week?
            </div>
          </div>
          <div className="flex justify-start">
            <div className="bg-gray-800 text-white px-4 py-3 rounded-lg max-w-[75%] text-sm">
              I hear you. It's important to find that work-life balance. How about we plan to grab coffee later this
              week?
            </div>
          </div>
          <div className="flex justify-start">
            <div className="bg-gray-800 text-white px-4 py-3 rounded-lg max-w-[75%] text-sm">
              I hear you. It's important to find that work-life balance. How about we plan to grab coffee later this
              week?
            </div>
          </div>
          <div className="flex justify-start">
            <div className="bg-gray-800 text-white px-4 py-3 rounded-lg max-w-[75%] text-sm">
              I hear you. It's important to find that work-life balance. How about we plan to grab coffee later this
              week?
            </div>
          </div>
          <div className="flex justify-start">
            <div className="bg-gray-800 text-white px-4 py-3 rounded-lg max-w-[75%] text-sm">
              I hear you. It's important to find that work-life balance. How about we plan to grab coffee later this
              week?
            </div>
          </div>
          <div className="flex justify-start">
            <div className="bg-gray-800 text-white px-4 py-3 rounded-lg max-w-[75%] text-sm">
              I hear you. It's important to find that work-life balance. How about we plan to grab coffee later this
              week?
            </div>
          </div>
          <div className="flex justify-start">
            <div className="bg-gray-800 text-white px-4 py-3 rounded-lg max-w-[75%] text-sm">
              I hear you. It's important to find that work-life balance. How about we plan to grab coffee later this
              week?
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
